### ISSUE TITLE
Installazione progetto 

### ISSUE THREAD

**Issue by lucacaputo09** [DTrombett/argo-dashboard#151]
Salve, una volta scaricato il file e decompresso su altervista come posso procedere?

**Comment by DTrombett** [comment]
Salve, il nostro sito è strutturato in JavaScript, con Next.js.
Può essere utilizzato da chiunque in sicurezza su https://argo-dashboard.vercel.app. In alternativa, puoi anche eseguirlo in locale, senza bisogno di alcun database o struttura esterna. Per farlo basta seguire le indicazioni presenti in [Contributing.md](https://github.com/DTrombett/argo-dashboard/blob/main/CONTRIBUTING.md), in particolare i primi 6 punti.
Se vuoi hostare pubblicamente per conto tuo il progetto, dovrai procurarti un host e assicurarti che supporti Next.js. Per https://argo-dashboard.vercel.app noi utilizziamo Vercel (gratuito). Non so se Altervista supporta Next perciò non saprei dirti.
Comunque ti sconsigliamo di hostare il progetto per conto tuo in quanto già lo forniamo noi pubblicamente e, inoltre, non essendo completo, potremmo modificare/aggiungere alcune cose e sarebbe difficile sincronizzare i cambiamenti.
