### ISSUE TITLE
Consiglio per la UI

### ISSUE THREAD

**Issue by itstermoh** [DTrombett/argo-dashboard#18]
Complimenti per il progetto, davvero. Sarebbe fantastico se aggiungessi un menu per scegliere la categoria come sull'app.

**Comment by DTrombett** [comment]
Grazie mille, mi fa piacere sapere che ti sia piaciuto questo progetto!
Attualmente questo sito è sviluppato per mettere al centro i dati essenziali che interessano di più e, quindi, non mostra ancora tutte le informazioni disponibili ma solo quelle più importanti. Aggiungere più sezioni è un'idea che mi piacerebbe molto implementare e probabilmente lo farò presto, dopo aver finalizzato le funzionalità principali.
